language: java
jdk:
 - oraclejdk8
install : true

before_install:
  - chmod +x gradlew

script :
 - sonar-scanner
cache:
 directories:
  $HOME/.m2/repository
  $HOME/.sonar/cache
  $HOME/.gradle
  .gradle
