language: java
jdk:
 - oraclejdk8
install : true

addons:
 sonarcloud:
  organization: "gkgjsrb-github"
  token:
    secure: SONAR_TOKE

before_install:
  - chmod +x gradlew

script :
 ./gradlew clean check sonarqube build
cache:
 directories:
 $HOME/.m2/repository
 $HOME/.sonar/cache
 $HOME/.gradle
 .gradle
